// ⚡️ ⚡️ ⚡️
// JSON data is NOT the same as what it would be if queried from
// MongoDB and therefore does not match the db.d.ts types because:
//   1. `timeLastPlayed` Dates are stringified
//   2. `timeLastPlayed` does not exist at all if not populated
// ⚡️ ⚡️ ⚡️

export const astroneers: Game[] = [
	{
		platform: 'Xbox',
		id: '361420',
		name: 'ASTRONEER',
		playtimeRecent: 0,
		playtimeTotal: 3799,
		timeLastPlayed: null, // ⚡️ This was done by me - JSON does not have the field at all if it doesn't exist
		achievements: [],
	},
	{
		platform: 'Steam',
		id: '361420',
		name: 'ASTRONEER',
		playtimeRecent: 0,
		playtimeTotal: 6788,
		achievements: [
			{
				id: 'TutorialDone',
				name: 'EXO Dynamics Training Seal of Approval',
				description: 'Complete the training missions.',
				completed: true,
				completedTime: 1643421249,
				globalCompleted: 57.8,
			},
			{
				id: 'HazardUprooted',
				name: 'Up By the Roots',
				description: 'Dig up a hazard.',
				completed: true,
				completedTime: 1643422837,
				globalCompleted: 64.6,
			},
			{
				id: 'ResearchChamber',
				name: 'Pursuit of Knowledge',
				description: 'Research an item in the Research Chamber.',
				completed: true,
				completedTime: 1643424560,
				globalCompleted: 63.2,
			},
			{
				id: 'InstantResearch',
				name: 'A Little Byte Goes a Long Way',
				description: 'Scan a Research Sample of any type.',
				completed: true,
				completedTime: 1642636385,
				globalCompleted: 74.3,
			},
			{
				id: 'SoilExtract',
				name: "Dirt Don't Hurt",
				description: 'Extract a resource using the Soil Centrifuge.',
				completed: true,
				completedTime: 1643424220,
				globalCompleted: 47.4,
			},
			{
				id: 'CatalyzeComponent',
				name: 'Do Science To It',
				description: 'Synthesize a composite material with the Chemistry Lab.',
				completed: true,
				completedTime: 1644101502,
				globalCompleted: 39.4,
			},
			{
				id: 'CollectGas',
				name: 'A Little Gassy',
				description: 'Collect a gas with the Atmospheric Condenser.',
				completed: true,
				completedTime: 1643419106,
				globalCompleted: 33.4,
			},
			{
				id: 'BuildRover',
				name: 'Sweet New Ride',
				description: 'Build a rover of any type.',
				completed: true,
				completedTime: 1643424394,
				globalCompleted: 50.8,
			},
			{
				id: 'UseShredder',
				name: 'Scrap for the Scrapper',
				description: 'Scrap an object in a Shredder.',
				completed: true,
				completedTime: 1643596171,
				globalCompleted: 37.7,
			},
			{
				id: 'TradePlatform',
				name: 'Junk Trader',
				description: 'Use the Trade Platform to exchange Scrap for another resource.',
				completed: true,
				completedTime: 1644443830,
				globalCompleted: 28.3,
			},
			{
				id: 'HardTerrain',
				name: 'Barrier Buster',
				description: 'Use a drill to deform a harder type of terrain.',
				completed: true,
				completedTime: 1645315120,
				globalCompleted: 19,
			},
			{
				id: 'GoMantle',
				name: 'Delve Greedily and Deep',
				description: 'Travel to the Mantle depth of any planet.',
				completed: true,
				completedTime: 1645322753,
				globalCompleted: 35.4,
			},
			{
				id: 'PlantSeed',
				name: 'Making a New Friend',
				description: 'Plant a seed.',
				completed: true,
				completedTime: 1643422845,
				globalCompleted: 40.7,
			},
			{
				id: 'ChangeSuit',
				name: 'Well Hello There, Fancypants',
				description: 'Change into a different suit.',
				completed: true,
				completedTime: 1644104216,
				globalCompleted: 56.1,
			},
			{
				id: 'PuzzleSolve',
				name: 'Thank You For Your Continued Assistance',
				description: 'Solve an EXO Dynamics Research Aid.',
				completed: true,
				completedTime: 1643423032,
				globalCompleted: 51.7,
			},
			{
				id: 'EveryComponent',
				name: 'Lab Rat',
				description: 'Use the Chemistry Lab to synthesize each composite material.',
				completed: true,
				completedTime: 1645557691,
				globalCompleted: 13,
			},
			{
				id: 'EveryGas',
				name: 'Gas Giant',
				description: 'Use the Atmospheric Condenser to collect every type of gas.',
				completed: true,
				completedTime: 1645204769,
				globalCompleted: 16.2,
			},
			{
				id: 'ScrapX',
				name: 'Chop Shop',
				description: 'Scrap 50 objects in a Shredder.',
				completed: true,
				completedTime: 1644446094,
				globalCompleted: 16.9,
			},
			{
				id: 'EverySeed',
				name: "In An Astroneer's Garden",
				description:
					'Plant a Spinelily, Lashleaf, Bouncevine, Wheezeweed, Thistlewhip, Popcoral and Daggeroot seed.',
				completed: true,
				completedTime: 1649222385,
				globalCompleted: 4.2,
			},
			{
				id: 'EveryRaw',
				name: 'Resources in the Rough',
				description: 'Use the Terrain Tool to harvest every type of raw material.',
				completed: true,
				completedTime: 1647980865,
				globalCompleted: 19.7,
			},
			{
				id: 'EverySmelt',
				name: 'They Who Smelt It',
				description: 'Use the Smelter to craft every type of refined resource.',
				completed: true,
				completedTime: 1644456335,
				globalCompleted: 28.7,
			},
			{
				id: 'BytesGain',
				name: 'Research Scientist',
				description: 'Gain 100,000 Bytes across all games.',
				completed: true,
				completedTime: 1643332908,
				globalCompleted: 28.2,
			},
			{
				id: 'BytesConcurrent',
				name: 'Information Dump',
				description: 'Reach more than 150 Bytes-Per-Minute of concurrent research.',
				completed: true,
				completedTime: 1643593063,
				globalCompleted: 51.4,
			},
			{
				id: 'ChamberAll',
				name: 'Secrets of the Universe',
				description: '',
				completed: true,
				completedTime: 1649211055,
				globalCompleted: 4.2,
			},
			{
				id: 'FindChamber',
				name: 'Shapes and Other Shapes',
				description: '',
				completed: true,
				completedTime: 1643593326,
				globalCompleted: 52.8,
			},
			{
				id: 'SolveChamber',
				name: 'First Step Into a Larger World',
				description: '',
				completed: true,
				completedTime: 1643597146,
				globalCompleted: 37.5,
			},
			{
				id: 'FindEngine',
				name: 'Encounter With the Infinite',
				description: '',
				completed: true,
				completedTime: 1645323602,
				globalCompleted: 26.5,
			},
			{
				id: 'SolveTerranEngine',
				name: 'Sylva Awakened',
				description: '',
				completed: true,
				completedTime: 1645324620,
				globalCompleted: 21.2,
			},
			{
				id: 'SolveBarrenEngine',
				name: 'Desolo Awakened',
				description: '',
				completed: true,
				completedTime: 1647810627,
				globalCompleted: 13.2,
			},
			{
				id: 'SolveAridEngine',
				name: 'Calidor Awakened',
				description: '',
				completed: true,
				completedTime: 1648177006,
				globalCompleted: 10.5,
			},
			{
				id: 'SolveExoticEngine',
				name: 'Vesania Awakened',
				description: '',
				completed: true,
				completedTime: 1648104592,
				globalCompleted: 10.2,
			},
			{
				id: 'SolveExomoonEngine',
				name: 'Novus Awakened',
				description: '',
				completed: true,
				completedTime: 1648934741,
				globalCompleted: 10.1,
			},
			{
				id: 'SolveTundraEngine',
				name: 'Glacio Awakened',
				description: '',
				completed: true,
				completedTime: 1649187518,
				globalCompleted: 10.6,
			},
			{
				id: 'SolveRadiatedEngine',
				name: 'Atrox Awakened',
				description: '',
				completed: true,
				completedTime: 1649221742,
				globalCompleted: 9.3,
			},
			{
				id: 'SolveAllEngines',
				name: 'To Infinity...',
				description: '',
				completed: true,
				completedTime: 1649221742,
				globalCompleted: 8.5,
			},
			{
				id: 'LeaveTerran',
				name: 'Blast Off',
				description: 'Use a shuttle to leave Sylva.',
				completed: true,
				completedTime: 1643419127,
				globalCompleted: 42.9,
			},
			{
				id: 'LandMoon',
				name: 'One Small Step',
				description: 'Visit Desolo.',
				completed: true,
				completedTime: 1643748705,
				globalCompleted: 35.7,
			},
			{
				id: 'LandArid',
				name: "It's a Dry Heat",
				description: 'Visit Calidor.',
				completed: true,
				completedTime: 1644984799,
				globalCompleted: 24.9,
			},
			{
				id: 'LandExotic',
				name: 'Into the Woods',
				description: 'Visit Vesania.',
				completed: true,
				completedTime: 1645240653,
				globalCompleted: 26.9,
			},
			{
				id: 'LandExoMoon',
				name: 'To the Forest Moon',
				description: 'Visit Novus.',
				completed: true,
				completedTime: 1644390146,
				globalCompleted: 27.7,
			},
			{
				id: 'LandRadiated',
				name: 'I Feel Sick',
				description: 'Visit Atrox.',
				completed: true,
				completedTime: 1643419145,
				globalCompleted: 23,
			},
			{
				id: 'LandTundra',
				name: 'Cool As Ice',
				description: 'Visit Glacio.',
				completed: true,
				completedTime: 1645203235,
				globalCompleted: 29.5,
			},
			{
				id: 'FastTravel',
				name: 'Now You See Me...',
				description: '',
				completed: true,
				completedTime: 1647650249,
				globalCompleted: 27.6,
			},
			{
				id: 'BeatGame',
				name: '...And Beyond',
				description: '',
				completed: true,
				completedTime: 1649221782,
				globalCompleted: 8.6,
			},
			{
				id: 'SlideTime',
				name: 'Hang 10-Squared',
				description: 'Slide uninterrupted for at least 10 seconds.',
				completed: true,
				completedTime: 1644815083,
				globalCompleted: 44.4,
			},
			{
				id: 'RoverAirtime',
				name: "Where We're Going, We Don't Need Roads",
				description: 'Drive an airborne rover for at least 10 seconds.',
				completed: true,
				completedTime: 1645323556,
				globalCompleted: 10.9,
			},
			{
				id: 'PlanetDance',
				name: 'Galactic Boogaloo',
				description: 'Dance on every planet.',
				completed: true,
				completedTime: 1645557262,
				globalCompleted: 5.6,
			},
			{
				id: 'BackpackFirework',
				name: "Baby You're a Firework",
				description: 'Launch 10 fireworks in 10 seconds.',
				completed: true,
				completedTime: 1649224471,
				globalCompleted: 3.6,
			},
			{
				id: 'MPSession',
				name: 'EXO Dynamics Outreach Participant',
				description: 'Join or host a multiplayer game session.',
				completed: true,
				completedTime: 1642573183,
				globalCompleted: 52.5,
			},
			{
				id: 'GuestResearch',
				name: 'Let Me Borrow This Just A Second',
				description: "Use a Research Chamber to research something in another Astroneer's game.",
				completed: true,
				completedTime: 1645669206,
				globalCompleted: 27.6,
			},
			{
				id: 'MPCore',
				name: 'Journey to the Center of the Thing',
				description: 'Travel to the center of any planet in a multiplayer game.',
				completed: true,
				completedTime: 1645323141,
				globalCompleted: 28.2,
			},
			{
				id: 'MPTime',
				name: 'EXO Dynamics Outreach Advocate',
				description: 'Spend more than 4 total hours in multiplayer sessions.',
				completed: true,
				completedTime: 1643596366,
				globalCompleted: 44.9,
			},
			{
				id: 'CoOpShuttle',
				name: 'Interplanetary Road Trip',
				description: 'Travel to another planet with another player in the same shuttle.',
				completed: true,
				completedTime: 1644812387,
				globalCompleted: 18.8,
			},
			{
				id: 'AllAchievements',
				name: 'EXO Dynamics Solar System Mastery',
				description: 'Obtain every Achievement in Astroneer.',
				completed: true,
				completedTime: 1649224474,
				globalCompleted: 2.4,
			},
			{
				id: 'WandererFirstProbe',
				name: 'The First Discovery',
				description: 'Use the Probe Scanner to find one of the mysterious Vintage Probes.',
				completed: true,
				completedTime: 1647649552,
				globalCompleted: 9.8,
			},
			{
				id: 'WandererAllProbes',
				name: "The Wanderer's Way",
				description: '',
				completed: true,
				completedTime: 1649222747,
				globalCompleted: 4.2,
			},
		],
		timeLastPlayed: new Date('2024-07-21T22:46:50.000Z'), // ⚡️ THIS WAS DONE BY ME - IT WAS A STRING IN JSON
	},
]
