import { Anek_Gujarati, Poppins } from 'next/font/google';
import clsx from 'clsx';
import '@/styles/globals.css';

const anek_gujarati = Anek_Gujarati({
	subsets: ['latin'],
	weight: '400',
	variable: '--font-anek-gujarati',
});

const poppins = Poppins({
	subsets: ['latin'],
	weight: '500',
	variable: '--font-poppins',
});

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en" className={clsx(anek_gujarati.variable, poppins.variable)}>
			<body>{children}</body>
		</html>
	);
};

export default RootLayout;
